name: flutter_application_1_repositories
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  bezier_chart: ^1.0.17+1
  shared_preferences: ^2.0.15
  flutter:
    sdk: flutter
  db_models:
    path: ../db_models
  services:
    path: ../services


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true